### ISSUE TITLE
Tutorial for Edge Probing Tasks

### ISSUE THREAD

**Issue by abhinavkashyap** [nyu-mll/jiant#1253] opened 2020-12-30 05:20 UTC
**Is your feature request related to a problem? Please describe.**
I am frustrated when I have to do edge probing tasks. Since unfortunately, ontonotes is not accessible, can you provide examples with dummy data in the CONLL format and how to run the edge probing tasks on these. 

**Describe the solution you'd like**

A tutorial notebook or markdown file on how to use the edge probing tasks in the new version of jiant.
Additionally, if I have some other dataset, then how should I format it so that I can run experiments on the new dataset.

**Describe alternatives you've considered**

- I have used the legacy version of jiant and it does not run out-of-the box. For example, I have to comment out a line regarding Openai-GPT tokenizer in the file `get_and_process_all_data.sh` and multiprocessing does not run the new MacOS. 
- I understand that the probing tasks are available as separate files in the new version of the repository. But there are no instructions on how to use them.

**Additional context**

**Comment by jeswan** [comment] 2020-12-31 05:33
Closing since it is a duplicate of #1252

**Comment by jeswan** [comment] 2020-12-31 05:33
Closing since it is a duplicate of #1252

**Closed by jeswan** 2020-12-31 05:33 UTC
